alias update="sudo apt update"
alias upgrade="pkcon update"
alias inst="sudo apt install "
alias ll="la -la"
alias cloq="tty-clock -cDsC 6"
alias gdep="git push heroku master && git push origin master"
alias dev="figlet dev-mode activated | lolcat ; code && /usr/bin/brave-browser-stable --force-device-scale-factor=1.2 %U"
